## Google's PageRank Algorithim

#### Algo Description:
1. Build matrix H (n x n) to model the hyperlinks
2. Build column vecotr w representing dangling nodes
3. Build matrix H(hat) = H + (w.1(T))/n to add equal probabilty for all webpages from dangling nodes
4. Build rank one matrix (1.1(T))/n to model equal probablity for any webpage at any time
5. Build Google Matrix G = theta * H(hat) + (1-theta) * (1.1(T))/n
6. Initilize column vector (pie)[0] = (1(T))/n
7. Iterate (pie)[k+1] = (pie)[k].G until (pie)* converges
8. Normalize and return (pie)*

#### Input Parameters:

A dictionary: 
- key : webpage
- value : list of webpages this webpage has a link to

A theta value:
- Value between (0,1) representing the % of time a user will use one of the links on the current webpage they are on.

#### Output Parameters:
A dictionary:
- key : webpage
- value : relative importance of the webpage


In [4]:
import numpy as np

In [22]:
def GooglePageRank(graph_dict, theta, max_iternations):
    
    n = len(graph_dict)
    
    H = np.zeros(shape=(n,n))
    w = np.empty(shape=(n,1))
    
    for key in graph_dict.keys():
        website = key
        links = graph_dict[key]
        weight = len(links)
        
        if weight == 0:
            w[website-1] = 1
        else:
            w[website-1] = 0

            for link in links:
                H[website-1][link-1] = 1/weight

    print("Matrix H: (web graph)")
    print(H)
    print()
    
    print("Matrix w: (dangling nodes)")
    print(w)
    print()
        
    w_hat = (1/n)*np.dot(w,np.ones((1,n)))
    print("Matric w_hat: (solving dangling nodes)")
    print(w_hat)
    print()
    
    H_hat = H + w_hat
    print("H_hat: (basic model)")
    print(H_hat)
    print()
    
    G_helper = (1/n)*np.ones((n,n))
    print("G_helper: (user model)")
    print(G_helper)
    print()

    G = theta*(H_hat) + (1-theta)*(G_helper)
    print("Google Matrix:")
    print(G)
    print()
    
    pie = (1/n)*np.ones((n,1)) 
    pie_prev = np.ones((n,n)) 
    
    
    iteration = 0
    while( (pie!=pie_prev).any() and iteration<50):
        iteration +=1
        pie_prev = pie
        pie = np.transpose(np.dot(np.transpose(pie),G))
    
    result_dict = {}
    index = 0
    
    for key in graph_dict.keys():
        result_dict[key] = pie[index][0]
        index+=1        
        
    return result_dict

In [23]:
test_dict = {
 1 : [2],
 2 : [1],
 3 : [1,3,5],
 4 : [3,5],
 5 : [],   
}

expected_result_85 = {
     1: 0.39412713724407505,
     2: 0.38033272574502336,
     3: 0.09011066221699261,
     4: 0.04531881257691794,
     5: 0.09011066221699261
}

theta = 0.85

In [24]:
GooglePageRank(test_dict, theta, 100)

Matrix H: (web graph)
[[0.         1.         0.         0.         0.        ]
 [1.         0.         0.         0.         0.        ]
 [0.33333333 0.         0.33333333 0.         0.33333333]
 [0.         0.         0.5        0.         0.5       ]
 [0.         0.         0.         0.         0.        ]]

Matrix w: (dangling nodes)
[[0.]
 [0.]
 [0.]
 [0.]
 [1.]]

Matric w_hat: (solving dangling nodes)
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.2 0.2 0.2 0.2 0.2]]

H_hat: (basic model)
[[0.         1.         0.         0.         0.        ]
 [1.         0.         0.         0.         0.        ]
 [0.33333333 0.         0.33333333 0.         0.33333333]
 [0.         0.         0.5        0.         0.5       ]
 [0.2        0.2        0.2        0.2        0.2       ]]

G_helper: (user model)
[[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]

Google Matrix:
[[0

{1: 0.39412713724407505,
 2: 0.38033272574502336,
 3: 0.09011066221699261,
 4: 0.04531881257691794,
 5: 0.09011066221699261}